### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by agoldis** [sorry-cypress/sorry-cypress#144]
@jhicken That's a ticket to track your effort on projects. From what I remember there're few leftovers: 

- [x] ~Fully functional project edit~
- [x] ~[Suggestion] Project human-friendly name~

**Comment by agoldis** [comment]
Thinking more about projects - this might be quite a big change for existing users.
One use case I am worried about is users running tests  that assign random projectIds.... it will be a mess.

Another example is the demo deployment on Heroku - random people run tests on it, every test has a different projectId.

Do you think we can create some kind of project-less setup?

**Comment by jhicken** [comment]
Yeah I'm glad your bringing this stuff up.

"One use case I am worried about is users running tests that assign random projectIds.... it will be a mess."

My question would be us this a realistic thing? It might be and my use cases just don't match it. Since your projectId is in your cypress.json it seems pretty static most of the time. Is cypress dashboard allowing for a dynamic projecteId?

The heroku case is kinda succy. And makes me think maybe we need to introduce some sort of list page search box to filter the projects list page.


"Do you think we can create some kind of project-less setup?"

Yeah... we could... It wouldn't be to difficult to implement an env var to disable projects or a special "all" project that shows all runs in the system. But i think I would instead vote for implementing a search feature as an alternative. I think that would get users where they want to be quicker in general. And continue to give them a more limited view of runs that are probably more relevant.

**Comment by jhicken** [comment]
A couple other things.

With project edit I was not planning on allowing users to rename projects. Seems like an edge case where that would be helpful. And it might be a pain to implement. 

However the hooks stuff that I'm currently working on should be editable on a project at anytime. 

Is there something else you were thinking of with "Fully functional project edit"?

Can you explain what you are thinking with this a little bit more? "[Suggestion] Project human-friendly name"

**Comment by agoldis** [comment]
Yeah, I am not sure if users are actually use as many different projects. It might be a super-edge case.

 > Is there something else you were thinking of with "Fully functional project edit"?
No, it jus wasn't clear what's the purpose of project edit if there's just project id and it's not editable. I didn't know you're planning to add more stuff in there. May be changing the icon / button to "configure" would be it more clear.

> Can you explain what you are thinking with this a little bit more? "[Suggestion] Project human-friendly name"

Yeah, I see "yc4ci4" for my project - it's been used in breadcrumbs and project name. Have an extra field on project entity like "Project name" would allow to display meaningful name to users. E.g. "web", while keeping the project id different.

**Comment by jhicken** [comment]
Cool thanks for the clarifications.

I can totally modify the edit icon ill put that in with my next pr.

The "yc4ci4" projectId you have is probably defined in your applications cypress.json file. Let me know if thats not the case. If that's the case you can literally put whatever you want as your projectId. I think that's neato.

**Comment by jhicken** [comment]
@agoldis can I remove this `[Suggestion] Project human-friendly name` or is there more that we need to discuss on it?

**Comment by agoldis** [comment]
> @agoldis can I remove this `[Suggestion] Project human-friendly name` or is there more that we need to discuss on it?

done
