### ISSUE TITLE
Reconsider docker-compose configuration

### ISSUE THREAD

**Issue by dlavrenuek** [sorry-cypress/sorry-cypress#190]
The current docker-compose files expose all ports to the host machine, which seems very odd to me. Combined with no authentication configuration for Mongo DB [docker-compose.full.yml](https://github.com/sorry-cypress/sorry-cypress/blob/master/docker-compose.full.yml#L7), it is just exposed to the outside and anyone can access it. There are tons of bots constantly scanning for open databases and you can see in #174 that these servers are actually hacked. 

When using docker-compose all containers have access to each other without having to expose the ports, so I would remove the exposed ports of mongo DB.

```
  mongo:
    image: mongo:4.0
```

Any ideas @agoldis ?

**Comment by agoldis** [comment]
Yeah, good point. I am not too concerned because it's just a matter of configuration and can easily be changed before deployment. I use docker-compose.yml for development and it's quite convenient to have all the ports open.

If you think people are just using docker-compose files as is, feel free to tighten the security. I wold leave the original docker-compose.yml for development though

**Comment by danielvianna** [comment]
I agree that it should be more secure out of the box to be newbie friendly.

**Comment by dlavrenuek** [comment]
I created a PR with a configuration that should be (hopefully) less prone to wrong usage and still provides full functionality of current docker-compose files: https://github.com/sorry-cypress/sorry-cypress/pull/192
