### ISSUE TITLE
Projects names with slashes will break UI

### ISSUE THREAD

**Issue by slinstaedt** [sorry-cypress/sorry-cypress#228]
## Summary

I tried to use my git's fully-qualified repo names (namespace/owner included) as project names for cypress, to be able to generate some link to the CI links (CI_URL), which is also using the fully-qualified names in URLs. Unfortunately though one is able to create such a project, the UI will "break" at some point (it neither requests the api for data, nor throw any exception). 

## How to reproduce
One can easily reproduce this issue: just create a new project "owner/my-project" at your heroku test installation and try navigating to this projects.

## Environment
latest version of all components (v1.0.0-beta.10)

**Comment by fsmaia** [comment]
It seems to be broken on 1.0.0-rc.9. Could you confirm?

**Comment by agoldis** [comment]
Fixed in #340

**Comment by fsmaia** [comment]
This bug is happening again in 2.0.0-beta.16.

At this time the URL works fine, but the sidebar links are broken (both `Latest runs` and `Project settings` buttons).

It is probably encoding this URL and replacing `/` with `%2F`.

Expected:
```
https://cypress.myorg.com/group/project/edit
```

Actual sidebar link:
```
https://cypress.myorg.com/group%3Fproject/edit
```

**Comment by fsmaia** [comment]
Doing some investigation:
- the `projectId` is properly set in the database, and the API application (GraphQL) brings it correctly too
- once the projects are loaded with `useGetProjectsQuery` there is no additional transformation (just some `decodeURIComponent` along the code, which shows evidence of the unwanted encoding bug)
- the `useGetProjectsQuery` hook seems to be correct too (both the query and the forwarding to `Apollo.useQuery`)

I'll take a deep look to find where the bug is 🤔
