### ISSUE TITLE
Jobs never timing out, timing out too soon

### ISSUE THREAD

**Issue by egramens** [sorry-cypress/sorry-cypress#299]
## Summary

A lot of the runs reporting into sorry-cypress are finished but are in the state of "waiting for inactivity timeout" for days while another job that is actually still running has reportedly timed out after 3 minutes of inactivity.

 ## Timed out too soon:
<img width="459" alt="Screen Shot 2021-03-22 at 2 23 08 PM" src="https://user-images.githubusercontent.com/65231753/112039314-4e0fc900-8b1a-11eb-807e-604c472c38ba.png">

## Still pending timeout:
<img width="530" alt="Screen Shot 2021-03-22 at 2 22 56 PM" src="https://user-images.githubusercontent.com/65231753/112039324-50722300-8b1a-11eb-9578-17c191704a53.png">

## Environment

- sorry-cypress version: `v1.0.0-rc.1`
- cypress version: `6.2.0`
- platform: `AWS`
- service: `director`

**Comment by agoldis** [comment]
Thanks @egramens!

Do you have any specs running for more than 3 minutes? If yes, I would recommend either splitting those specs or increasing the inactivity timeout for the project. 

I will take care of the stage runs, issue.

**Comment by egramens** [comment]
@agoldis So we have 2 types of tests, regular CICD tests that generally take between 1 and 3 mins per spec, though some are around 3m30s per spec. The other type are e2e tests that run serially and can take 15m per spec to several hours sometimes if there are errors.

**Comment by agoldis** [comment]
Hmm... seems like the [inactivity timeout](https://docs.sorry-cypress.dev/concepts/inactivity-timeout) concept wouldn't work well for 15 minutes case...  

Are you using hooks for integrating with GH / Bitbucket?

**Comment by egramens** [comment]
We are using Gitlab CI and running cypress tests via a handful of pipeline jobs. I'm reconfiguring the cypress agent to point to our sorry-cypress endpoint in our AWS environment.

The cypress runs use these flags:
`cypress run --parallel --record --key "$CI_COMMIT_SHA" --ci-build-id "$CI_COMMIT_SHA" --group "$TEST_SUITE"`

where `$CI_COMMIT_SHA` is the build-in CI commit short SHA value, and `$TEST_SUITE` is the name of the group of tests. 

Anything wrong with that combination of flags and values?

**Comment by BHunter2889** [comment]
We're also having similar issues. We're using a series of data hydrations within several specs that may have 100+ unique hydrations, thus running a test for each in what is typically a "small spec" of just two base tests.

Unfortunately. We're also unable to set the timeout ourselves either because the UI doesn't load with project settings or the home page. It only loads the "All runs" page for the lone project we have running in it at the moment which doesn't have any menus or header or footer like I've seen in screenshots of sorry-cypress. I've been wondering if this isn't an issue with the helm chart provided that we deploy into our on-prem k8s somehow as using the docker-compose seems to provide the intended functionality locally. Unfortunately local usage does not provide us any value as we are running this as part of our GitLab CI process as well.

**Comment by agoldis** [comment]
@egramens sorry for the delayed response.

Your setup looks good.


@egramens @BHunter2889 
The problem is with the recent implementation of inactivity timeout. See the [discussion here](https://github.com/sorry-cypress/sorry-cypress/discussions/287). 

We were trying to reliably detect when runs complete, but it's not trivial and doesn't work well with long-running specs - it marks the runs as timed out after 3 minutes (the default) of inactivity. I never imagines a single spec would run for more than 10 minutes at all. 

I am planning to iterate on that problem again soon, meanwhile, unfortunately, I cannot suggest a good solution.

**Comment by agoldis** [comment]
@BHunter2889 
Seems like you're not seeing the most recent version. I was sure that providing the `latest` tag pulls the most recent docker image, am I right @tico24?

What's the version you're seeing in the footer? E.g. https://sorry-cypress-demo.herokuapp.com runs `v1.0.0-rc.5`

**Comment by tim-sendible** [comment]
The helm chart doesn't pull latest by default. It's pinned to the last stable version. 

You can set latest in the values.yml. Be sure to set the imagePullPolicy to always too.

**Comment by agoldis** [comment]
FYI, I am planning to deprecate inactivity timeout alltogether and report completion per-group. That's planned to be implemented in the upcoming weeks.

**Comment by vishnuprabhu-95** [comment]
Awesome @agoldis . I will be eagerly waiting for the same. It will help our team to run each spec files for long run (2hr - 3hr).
Thanks in advance.
