### ISSUE TITLE
Allow reusing --ci-build-id  after a timeout

### ISSUE THREAD

**Issue by Postavshik** [sorry-cypress/sorry-cypress#31]
I have run docker-compose up, changed the configuration of cypress and was able to run tests in two parallel threads. After initial test run I am not able to make a second test run. Looks like service sees that test run exists in the dashboard and skipping test run.

When I make docker-compose down and then docker-compose up again, I can make single run but the second run doesn't work again.

Am I missing something in configuration?

**Comment by agoldis** [comment]
Did you provide a different build id for the second run?

**Comment by Postavshik** [comment]
No, do I have to?

**Comment by agoldis** [comment]
Yes, that's how it knows that a new run has started and it wasn't a new machine for an old run

**Comment by agoldis** [comment]
Let me know if that worked for you 😃 if not, please copy your commands here

**Comment by Postavshik** [comment]
hm... so I need randomize build id somehow... is it possible to configure to delete the completed build after test run? :)

**Comment by agoldis** [comment]
It is possible but not supported today.

What the original cypress dashboard does is using a  "timeout" for each
build.

Sometimes it takes a while to spin up new cypress agents, e.g. on cloud CI
environment when each new agent is created on demand.

I suggest using commit-id+branch or some git-related data (if you use git)
so that each agent will use the same buildId l, bit when the system under
test changes, a new build id will be generated.

So far I didn't see many requests to implement that, but feel free to
create one, let's see how popular this requirement would be.

**Comment by Postavshik** [comment]
Thank you very much for your help :)

**Comment by Postavshik** [comment]
Here is a hacky solution I have found so far to use just npm script
`"cy:run_p": "cypress run --parallel --record --key xxx --ci-build-id $RUNID",
    "cy:two": "npm run cy:run_p & npm run cy:run_p",
    "cy:run_multi": "RUNID=$(uuid) npm run cy:two",`

so command `cy:run_multi` with trigger two threads at the same time with unique ID every time

**Comment by agoldis** [comment]
@Postavshik thanks for sharing that script here, closing the issue as part of a cleanup
