### ISSUE TITLE
Jenkins Integration?

### ISSUE THREAD

**Issue by RicardoVaranda** [sorry-cypress/sorry-cypress#35]
Hi @agoldis ,

First of all, great work! Just had a quick read through the source code and this is some amazing stuff you have done here. I've got a couple of questions I'd love if you could explain.

- How would the dashboard integration with a CI tool? e.g. Jenkins
- Where is the parallelisation happening? i.e in the CI tool or in the dashboard itself?
- Where are tests actually running? 

For the last question let me give you a bit of context.

Say we are doing a bit of custom things within cypress for example you install a package which does not come out of the box and then within cypress you execute a task in order to have that package execute some logic.

Taking that use case into consideration where are tests actually ran? The reason I'm asking is because if they are in the director how does it know which packages it needs to have installed before running the tests etc.

Thank you for your time!

**Comment by agoldis** [comment]
Hi @RicardoVaranda! Thanks for the kind words!

> How would the dashboard integration with a CI tool? e.g. Jenkins

The "dashboard" is just docker container. You can either:
- spin up the container as part of jenkins run
- have it running as a permanent service

Note that depending on your needs you would need to attach a permanent storage to keep test results.

> Where is the parallelization happening? i.e in the CI tool or in the dashboard itself?

On both :) you need CI environment to run tests, and a "coordinator" to assign tests to each individual agent. The "dashboard" serves the coordination role, it gets requests from individual cypress agents and assigns a task one after another. That's how "parallelization" is achieved.

> Where are tests actually running?

On your CI environment. This project is just a replacement for paid cypress "dashboard" service the unlocks paid features and allows on-premise installation. 

You just run `cypress run` as usual, but with [tweaked configuration](https://github.com/agoldis/sorry-cypress#Reconfiguring-Cypress). the agents are contacting the custom "dashboard" (this project) instead of the original one.

Let me know

**Comment by agoldis** [comment]
For reference: https://sorry-cypress.dev/ci/jenkins

**Comment by slutske22** [comment]
https://docs.sorry-cypress.dev/ci/jenkins says under construction.  Do you have any links to tutorials / recommendations on how to set up a Jenkins pipeline to leverage sorry-cypress to run cypress tests in parallel across multiple jenkins agents?

**Comment by agoldis** [comment]
@slutske22 that's the only I am aware of https://crumbhole.com/sorry-cypress-in-a-kubernetes-jenkins-pipeline/

**Comment by birkle-it** [comment]
Did you manage to get sorry cypress integrated with jenkins ?

**Comment by slutske22** [comment]
@birkle-it  yes I did, wrote an article about it here https://medium.com/geekculture/parallelizing-cypress-with-jenkins-aws-and-sorry-cypress-8241331fe50f
