### ISSUE TITLE
Screenshots not uploading to Azure Storage

### ISSUE THREAD

**Issue by IanMoroney** [sorry-cypress/sorry-cypress#600]
Please note - issues that are not following the template will be closed automatically:

- [ x] I have verified that all sorry-cypress services are running and accessible
- [ x] I have read documentation and found no answer to my problem
- [ x] I have searched issues / discussions and found to answer to my problem
- [ x] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [ x] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary

Required header `x-ms-blob-type` is not being set when uploading screenshots to Azure Storage

## How to reproduce

1. Provision azure storage account
2. Use new azure screenshots driver
3. Execute cypress tests in debug mode

```
'StatusCodeError: 400 - "<?xml version=\\"1.0\\" encoding=\\"utf-8\\"?>\\n<Error><Code>MissingRequiredHeader</Code><Message>An HTTP header that&apos;s mandatory for this request is not specified.\\nRequestId:629f8e17-601e-0022-3517-95da9a000000\\nTime:2022-07-11T11:16:48.5754318Z</Message><HeaderName>x-ms-blob-type</HeaderName>
```
Full stack trace: https://gist.github.com/IanMoroney/ae978defe37b7f5b8a01fd689ab6b2d4

According to the [Microsoft documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob#request-headers-all-blob-types), this header is required.

## Environment

- sorry-cypress version: 2.1.6
- cypress version: `9.7.0`
- platform: `kubernetes via helm`
- service: `director`

**Comment by IanMoroney** [comment]
@Hackatosh , is it possible to set the `x-ms-blob-type` header somewhere in the driver? I couldn't see an obvious location where to put it

**Comment by Hackatosh** [comment]
I will need some help on this as I am not familiar with the runner code of Cypress

**Comment by IanMoroney** [comment]
Me either.
I can't find references to `screenshot` or `upload` in the cy2 project yet, so not actually familiar with how it works.

**Comment by Hackatosh** [comment]
cy2 is a little project written by @agoldis to patch the cypress runner code in order to target Sorry Cypress instead of Cypress. The code we need to patch is located somewhere in this repo I think : https://github.com/cypress-io/cypress

**Comment by agoldis** [comment]
@Hackatosh any chance you have discovered any other workarounds? Really would like to avoid being too intrusive with cy2?

**Comment by cadbury-sdmjc** [comment]
I came across this issue today so I'm pleased to see that someone else has raised it already. Since the header is required by MS, and cypress aren't going to support uploading directly to Azure as they want you to use their hosted service, I think the only other option would be to proxy the request through sorry-cypress somehow and have sorry-cypress add in the header.

My preference would be for patching it with cy2.

**Comment by IanMoroney** [comment]
I kind of agree with @cadbury-sdmjc 
If cy2 is used to patch cypress, perhaps it would be useful to expand it to also handle this use case.
@agoldis, would you be open to something like this?

**Comment by IanMoroney** [comment]
That could work yep!
Would you consider cloning cy2 under `agoldis` as `cy2-azure`? it would be good to have it held under the same banner for visibility

**Comment by IanMoroney** [comment]
@agoldis , any thoughts on the above? thanks!

**Comment by agoldis** [comment]
Here we go https://github.com/sorry-cypress/cy2-azure

**Comment by IanMoroney** [comment]
Thank you very much @agoldis !
Would you immediately know how to patch `upload.js` with `azure-cy2` ? or is it something that would have to be worked out?
I'm not yet familiar with how cy2 does its url substitution, so not sure how hard it would be to intercept the uploader and inject the header, so not actually sure where to start, but I'd like to help if I can!

**Comment by Hackatosh** [comment]
Hello ! I have made a PR in order to implement the patching of `upload.js` : https://github.com/sorry-cypress/cy2-azure/pull/1 

I still need to update the tests though. Could you please activate the tests on CircleCI for this repository please ?

Also, I am not quite sure how the case where CYPRESS_PACKAGE_CONFIG_PATH is provided should behave. What I have implemented is that you can pass CYPRESS_PACKAGE_CONFIG_PATH in order to customize the path of your configuration file, but you automatically discover where upload.js is located in any case.
Maybe if CYPRESS_PACKAGE_CONFIG_PATH is provided we need to resolve the path of upload.js relatively to the configuration file provided ?

**Comment by agoldis** [comment]
re: Could you please activate the tests on CircleCI for this repository please ?
✅ done

re: `CYPRESS_PACKAGE_CONFIG_PATH`
I think it would make sense to patch `../lib/upload.js` based on `CYPRESS_PACKAGE_CONFIG_PATH` - let's start with this approach and see what happens.


Thanks a lot for your contribution!

**Comment by agoldis** [comment]
Should be working with https://github.com/sorry-cypress/cy2-azure/pull/1
