### ISSUE TITLE
AWS CloudFormation template uses deprecated S3 AccessControl Property

### ISSUE THREAD

**Issue by jonlinkens** [sorry-cypress/sorry-cypress#809]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/sorry-cypress/sorry-cypress/issues?q=is%3Aopen+is%3Aissue) and [discussions](https://github.com/sorry-cypress/sorry-cypress/discussions).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have read the [documentation](https://docs.sorry-cypress.dev/) and found no answer to my problem

### Environment information

<details>

```
  - sorry-cypress version: `2.5.7`
  - cypress version: `12`
  - cy2 version: `--`
  - platform: `AWS`
  - service: `all`

```

</details>

### Describe the bug

When running the one click CloudFormation Template on AWS (found on [this page](https://docs.sorry-cypress.dev/cloud-setup/aws)) it will give an `InvalidBucketAclWithObjectOwnership` error and not deploy the stack as expected.

I believe this is because[ Amazon have disabled all access control lists for all newly created S3 buckets after April 2023](https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/), and the template is still using the `AccessControl` property.

This error can be fixed with the following change (there might be better config here still, this just worked for me):
```diff
S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", [!Ref "AWS::StackName", "test-results"]]
-     AccessControl: PublicRead
+     PublicAccessBlockConfiguration:
+       BlockPublicAcls: false
+     OwnershipControls:
+        Rules:
+          - ObjectOwnership: ObjectWriter
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - "POST"
              - "GET"
              - "PUT"
              - "DELETE"
              - "HEAD"
            AllowedOrigins:
              - "*"
​
```

### Expected behavior

That the template works and the stack is created without error.

### Reproduction steps

Deploy the CloudFormation template on AWS by clicking [here](https://console.aws.amazon.com/cloudformation/home#/stacks/new?stackName=sorry-cypress&templateURL=https://s3.amazonaws.com/agoldis.dev/sorry-cypress/sorry-cypress-stack.yml). After stack creation there will be an error with the S3 bucket and it will roll back.

Additionally, S3 buckets need to be globally unique - which is not really documented anywhere and will cause the stack creation to fail even before this! It would be good to advise editing the template's S3 names to ensure that people do not encounter this.

### Full log and debug output

<details>

```
--
```

</details>

**Comment by redbugz** [comment]
There is a stack parameter `StackName` to set a unique name, but it didn't work for me, it still used the actual stack name of `sorry-cypress` not the unique name I set in the template, so after deleting the stack, I set the actual stack name to a unique name and then it worked, up until this current issue here. So yes, the unique name prefix either needs to be referenced correctly in the stack template, or the instructions need to switch to tell you to make sure the actual stack name is unique as well

**Comment by agoldis** [comment]
@redbugz any idea why? All the resources are dependant on stack name: https://github.com/sorry-cypress/sorry-cypress/blob/34f1aa8daa8a1bc2233c03e7ff8f039981a97239/cloudformation/sorry-cypress.yml#L315

**Comment by redbugz** [comment]
> @redbugz any idea why? All the resources are dependant on stack name:
> 
> https://github.com/sorry-cypress/sorry-cypress/blob/34f1aa8daa8a1bc2233c03e7ff8f039981a97239/cloudformation/sorry-cypress.yml#L315

I'm a noob at CloudFormation templates so I'm just learning this myself. I'm thinking it has to do with this:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-stackname
This states the `AWS::StackName` is the name given in the create stack command which I assume is mapped to the stack name you eneter when creating the stack, which defaults to `sorry-cypress` from your link.
However, when referencing a Parameter, the docs don't show that you prefix it with `AWS::`, so the Ref for the unique stack name parameter I think would just be `StackName`. There is a bit of confusing since they are the same name, just one with `AWS::` on the front? So from what I can tell, the unique stack name parameter is never used, only the built-in pseudo param, so we should either instruct people to set the stack name in the UI to a unique name, or change the template to remove the `AWS::` prefix from `StackName` so it uses the unique name parameter, instead of the 

Also, I ran into an issue where my unique name was too long, and one of the resources (I believe the target group or security group name) exceeded a length of 32 characters. My unique name was `sorry-cypress-{8 letter project name}`. I switched to `{2 letter prefix}-sorry-cypress` to keep under the 32 character limit.
Looking at the template the dashboard target group name appends 13 characters `-dashboard-tg`, so the unique name would have to be limited to 19 characters, and my first unique attempt was 22 characters. The default of `sorry-cypress-unique`, which I don't think is ever actually used anyway, just barely meets the requirements being 19 characters long, so any name longer than that will fail.
