### ISSUE TITLE
Consider Renaming project

### ISSUE THREAD

**Issue by redbugz** [sorry-cypress/sorry-cypress#877]
- [x] I have searched issues for similar feature requests

## What is this feature about (1 sentence)
Consider renaming project to avoid conflict with Cypress

## Why is it needed? What is the value? For whom do we build it?
https://www.cypress.io/blog/2023/11/07/update-defense-intellectual-property

I don't know the history or background and if they are being reasonable or not, and I know it's a big pain to rename, but could we consider it if it would help allow this project to continue as an option for our Cypress tests?
I would be willing to help with all the tedium of updating everything in the project if it would allow it to continue.

**Comment by agoldis** [comment]
Of course, we can rename it, but it won't help - Cypress.io will block it because they just don't want it to exist, regardless of the name.

**Comment by 403-html** [comment]
https://github.com/sorry-cypress/sorry-cypress/discussions/283

As you can see there was already a discussion about it, for 2 years the Cypress team didn't reach the maintenance team, Why should they care now? It's not now about naming (which is not a trademark issue, since Cypress [doesn't have a trademark](https://uspto.report/TM/97870603) **yet**), but about up-keep of the business and removing physically (not by economic ways) the competition. Especially one that provides cheaper maintenance of its services (and therefore lower prices to customers) than you do.

**Comment by redbugz** [comment]
@agoldis I assume they have been in contact with you. I only know what the blog post says. The messaging in the blog post is messy and inconsistent, because they attribute to sorry-cypress many things not related to sorry-cypress but are really Currents.dev. But all of their beefs seem to be with Currents, not sorry-cypress (other than the name).
So when they say things like:

> Cypress remains committed to open source and our mission. We view development of plugins as a critical part of a healthy community, including those that compete with the capabilities of our commercial product.

The seems to indicate a willingness to allow an open source non-commercial tool like sorry-cypress to exist, as long as it doesn't infringe on their name/content/etc. So if we rename the project and remove any problematic references/images/etc of which I don't think there are that many, that seems to take away their primary complaint, which is about name infringement and a competing commercial service, which sorry-cypress is not. I know they conflate them, so I'm trying to judge if they really believe what they say, or if they are being disingenuous in their blog post.

If however, in their communication with you, they have make it clear that even if sorry-cypress changes their name and doesn't use any of their name/images/etc. that they will still block any effort to have an open source dashboard/parallelization effort, then you are right there is no point. Other than of course as it gains playwright support, sorry-cypress is no longer the best name either.

So what I'm hoping is that by making a much clearer distinction and break between the sorry-cypress open source project, and the Currents.dev commercial project, that at least sorry-cypress can continue to work with Cypress under a different name. It is clear they will always attempt to block Currents.dev, so I assume you will just have to go forward as primarily a Playwright dashboard there, unless you can figure out some way to make that work.

I assume that also means that cypress-cloud or a fork of it would have to move into community ownership, as I assume you won't want to maintain the Cypress integration.

**Comment by 403-html** [comment]
why Meta having React doesn't have beef with Preact team, or Kubernetes, an owner of k8s doesn't have beef with k3s? 

"Cypress" name is not a trademark, so it's a non-sense beef from their side. It's all about money and that there is possibility that someone can use for dashboard something else than their paid solution (doesn't matter if it's open-source self hosted sorry-cypress, or cloud hosted Currents).

If you see for yourself on the blog posts (yes, there are two for this topic) you will notice the statement that it is **for the benefit of users**. Huh? The best thing for users is competition in the industry. This causes constant development, fighting for customers, reducing prices, optimizing processes. If Cypress can't crank out anything to compete with Currents cloud solution, or sorry-cypress (here for sorry-cypress, the only thing they could do would be to make their dashboard a fully self hosted option as well), then they resort to the ultimate - physically blocking the competition.

**Comment by agoldis** [comment]
@redbugz @403-html 

Thanks for your feedback and for being vocal. Those are all valid points!

I wouldn't attribute too much to interpreting their message and trying to decrypt signals - their ultimate goal is to monetize cypress, and all the rest is secondary - a PR effort aimed to give legitimacy to their decisions. One additional aspect of the publication is an attempt to ruin my reputation by framing and putting things out of context. Of course, there's more to the story than can be publicized, it's not in Cypress's favour. More facts will become public one day. For now, let's focus on the problem.

We are taking actions to deescalate and to address the claims they presented:

- We now host our binaries (see https://currents.dev/readme/integration-with-cypress/alternative-cypress-binaries) that you can use easily - those are block-free and are not prone to cypress shenanigans. Also, we are paying ourselves for the distribution
- The project and the package names will be renamed, and the governance will change as well. We are now consulting with the stakeholders (mostly my wife 😂) to figure out the details and to plan our commitments. 

I am sure their leadership will still be unhappy because that means they won't get the customers they want to get, but at least they won't have a spin on the naming.

Stay tuned!

**Comment by mesudip** [comment]
Cypress Team fell into the `open-source` hype and tried to used it for marketing. I don't think they even care about the `open-source`. 

Irritating fact is that `sorry-cypress` (MIT license) is using `cypress` (MIT License), and Cypress Team is unhappy about it.. Well, what's the point of having the project open-sourced when you don't want people to create derivative of your project ..! 
Also what do you call a work derived from open-source  project `cypress`? Well it's natural to have term `cypress` somewhere. But gotta admit that the  term `sorry-cypress` is quiet provocative.

Cypress team wants the open-source community to contribute, but in their own terms and only in a way that it benefits their ecosystem and commercial cause. This mentality is a plague to the open-source philosophy.

Under their present license, What Currents is doing is perfectly valid.And  what they are trying to do to `sorry-cypress` and Currents business is outright wrong. Things they can try out are.
- Move entire cypress code to BSL from MIT. I don't know if we can call Cypress open-source after that but this will have 0 effect on sorry-Cypress as I can still self host it. This  will invalidate Currents business.
- Release  cypress dashboard  Under BSL and then compete with `sorry-cypress` and Currents. 

It's becomes tricky when companies start with 
> We are working on something great and useful and are willing to share it with everyone. let's join our hands. 

And when they realize that others can create new business out of it
> Its my Software, I've worked  and invested on it and others shouldn't be able to make money from it. I want all the  money for myself.
